version: '3.8'

services:

  postgres:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hubBook
    ports:
      - "5432:5432"
    volumes:
      - ./docker_db_init/:/docker-entrypoint-initdb.d/
